apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: php-74
  namespace: nextcloud
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/cuppett/ubi8-php74:latest'
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source